### ISSUE TITLE
Bug: ffmpeg directory not writable by mstream user

### ISSUE THREAD

**Issue by tidux** [linuxserver/docker-mstream#13]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------
The directory /opt/mstream/bin/ffmpeg/ needs to have group ownership set to "abc" or "users" instead of "root" to allow extraction to proceed. 

See https://github.com/IrosTheBeggar/mStream/issues/359

## Environment
**OS:** Slackware Linux 15.0
**CPU architecture:** x86_64
**How docker service was installed:** binaries from docker.io

## Command used to create docker container (run/create/compose/screenshot)
`docker-compose up -f mstream.yaml -d`.  Contents of `mstream.yaml`:
```
---
version: "2.1"
services:
  mstream:
    image: lscr.io/linuxserver/mstream
    container_name: mstream
    environment:
      - PUID=1000
      - PGID=100
      - TZ=US/Pacific
    volumes:
      - /var/lib/mstream:/config
      - /var/lib/music:/music
    ports:
      - 127.0.0.1:3000:3000
    restart: unless-stopped
```

## Docker logs
n/a
