### ISSUE TITLE
ValidationError: "folders.library" must be of type object

### ISSUE THREAD

**Issue by NoxInmortus** [linuxserver/docker-mstream#2]
Hello,

I'm currently running into an issue with mstream.

Container loop with this error :
```
2019-10-24T16:16:42.905Z error: Config Validation Failed
Error: ValidationError: "folders.library" must be of type object
    at Object.exports.setup (/opt/mstream/modules/defaults.js:76:11)
    at Object.exports.serveIt (/opt/mstream/mstream.js:20:24)
    at Object.<anonymous> (/opt/mstream/cli-boot-wrapper.js:41:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
```
It was working fine for a few months. I use watchtower to auto-update and it seems it downloaded 3 images in the last 2 days :
```
root@scw-imp-media2:[~]: docker images|grep mstrea
linuxserver/mstream         latest              269730ec6eda        21 minutes ago      255MB
linuxserver/mstream         <none>              fa29f8d68fb2        8 hours ago         255MB
linuxserver/mstream         <none>              2821e16ac095        29 hours ago        159MB
linuxserver/mstream         <none>              4ba45a15cdb2        2 weeks ago         159MB
```
And it stopped working 8 hours ago, so with image labelled at  fa29f8d68fb2.

this is my setup :
```
  - name: mstream
    image: linuxserver/mstream:fa29f8d68fb2
    restart_policy: unless-stopped
    env:
      PUID: '1800'
      PGID: '1800'
      TZ: Europe/Paris
      USE_JSON: 'true'
    volumes:
      - mstream:/config
      - /mnt/s3-imp/music:/music:ro
    ports:
      - 3000:3000
```
Running on debian 9.9 with docker version 19.03.1

Thanks for your insights.
